#!/bin/sh
create_command_bin() {
SCRIPT=$1
if [ ! -e ${TARGET_BIN}/${SCRIPT} ]; then
        cd ${TARGET_BIN}; ln -s ansible-wrapper.sh ${SCRIPT}
else
        echo "${TARGET_BIN}/${SCRIPT} already exist, will not update it"
fi
}

if [ ! -e ${TARGET_BIN}/${SCRIPT} ]; then
        echo "Failed to create ${TARGET_BIN}/${SCRIPT}"
        exit 1
fi

# Commands to create
COMMANDS="ansible \
ansible-config \
ansible-console \
ansible-galaxy \
ansible-playbook \
ansible-vault \
ansible-community \
ansible-connection \
ansible-doc \
ansible-inventory \
ansible-test \
ansible-lint \
ansible-pull"

# determime target root directory
# either /usr/local/bin or current user ~/bin
if [ -d /host/usr/local/bin ]; then
        TARGET_ROOT=/host/usr/local
elif [ -d /host/bin ] ; then
        TARGET_ROOT=/host
else
        echo "could not determine copy target"
        exit 1
fi

TARGET_BIN=${TARGET_ROOT}/bin
TARGET_SHARE=${TARGET_ROOT}/share/ansible-container

cp -v /container/ansible-wrapper.sh ${TARGET_BIN}/ansible-wrapper.sh

for COMMAND in ${COMMANDS}; do
    create_command_bin ${COMMAND}
done

# Create container share area under /usr/local/share if it doesn't exist
if [ ! -d ${TARGET_SHARE} ]; then
        mkdir -p ${TARGET_SHARE}
fi

# Copy examples to container share area, overwriting any previous content.
cp -av /container/examples ${TARGET_SHARE}/
