---
- name: Ensure Alpha Host Setup
  hosts: alphost
  tasks:
    - name: Site | hello world
      ansible.builtin.command: echo "Hi! Ansible is working"
      changed_when: false

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Ensure NetworkManager is installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - NetworkManager

    - name: Deactivate Wireless Network Interfaces
      ansible.builtin.command: nmcli radio wifi off
      become: true
      when: "'NetworkManager' in ansible_facts.packages"
      changed_when: false

    - name: Test ssh
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
      delegate_to: localhost

    - name: Test webpage access
      ansible.builtin.uri:
        url: https://www.example.com
        return_content: true
      register: webpage
