---
# Ansible Playbook: Manage Kea DHCPV4 Server Workload on ALP Host
# Description: This Ansible playbook automates the setup of the Kea DHCPV4 server workload
# on an ALP host. It follows the steps documented in the URL provided below.
# Kea Workload Documentation: https://build.opensuse.org/package/view_file/SUSE:ALP:Workloads/kea-container/README.md?expand=1

- name: Deploying and Managing the Kea DHCP server workload
  hosts: alphost
  become: true
  vars:
    workload:
      name: kea
      image: registry.opensuse.org/suse/alp/workloads/tumbleweed_containerfiles/suse/alp/workloads/kea:latest

  tasks:
    - name: Pull the Kea DHCP server container image
      containers.podman.podman_image:
        name: "{{ workload.image }}"
        state: present

    - name: Install all required parts of the Kea workload
      ansible.builtin.command: >-
        podman container runlabel install {{ workload.image }}
      register: workload_runlabel_install
      changed_when:
        - ('already exist' not in workload_runlabel_install.stdout)

    - name: Add firewall exception rule for DHCP
      ansible.posix.firewalld:
        service: dhcp
        permanent: true
        state: enabled
        immediate: true

    - name: Configure Kea DHCPv4 using template
      ansible.builtin.template:
        src: "kea-dhcp4.conf.j2"
        dest: "/etc/kea/kea-dhcp4.conf"
        mode: '0644'
      notify: Reload Kea configuration

    - name: Start Kea DHCPv4 server using systemd
      ansible.builtin.systemd:
        name: kea-dhcp4.service
        state: started
        enabled: true

  handlers:
    - name: Reload Kea configuration
      ansible.builtin.command: /usr/local/bin/keactrl reload
      register: kea_reload_result
      changed_when:
        - '"INFO/keactrl: Reloading kea-dhcp4..." in kea_reload_result.stdout'
