---
# Ansible Playbook: Setup Cockpit Web server on ALP Dolomite
# Description: This Ansible playbook automates the deployment of the Cockpit Web server on an ALP Dolomite host.
# The steps are based on: [https://documentation.suse.com/alp/dolomite/html/alp-dolomite/available-alp-workloads.html#task-run-cockpit-with-podman]
# Administering SUSE ALP Dolomite using Cockpit Documentation: [https://documentation.suse.com/alp/dolomite/single-html/cockpit-alp-dolomite/]

- name: Setup Cockpit Web server
  hosts: alphost
  become: true
  vars:
    workload:
      name: cockpit-ws
      image: registry.opensuse.org/suse/alp/workloads/tumbleweed_containerfiles/suse/alp/workloads/cockpit-ws:latest

  tasks:
    - name: Install required packages, if any, for workload {{ workload.name }}
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      notify: Reboot
      loop:
        - cockpit-bridge
        - cockpit-tukit

    - name: Reboot right now if necessary
      ansible.builtin.meta: flush_handlers

    - name: Retrieve image for workload {{ workload.name }}
      containers.podman.podman_image:
        name: "{{ workload.image }}"
        state: present

    - name: Install Cockpit Web server container
      ansible.builtin.command: >-
        podman container runlabel install {{ workload.image }}
      register: workload_runlabel_install
      changed_when:
        - ('already exist' not in workload_runlabel_install.stdout)

    - name: Ensure service can be started for workload {{ workload.name }}
      ansible.builtin.systemd_service:
        name: "cockpit.service"
        state: "started"
        enabled: true

    - name: Inform user to access the Cockpit Web user interface
      ansible.builtin.debug:
        msg: >-
          Cockpit Web UI is running on https://{{ ansible_default_ipv4.address }}:9090
          Please accept the warning about the self-signed SSL certificate to access it.

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 600
        post_reboot_delay: 60
