---
# Ansible Playbook: Manage Kea DHCPV6 Server Workload on ALP Host
# Description: This Ansible playbook automates the setup of the Kea DHCP server workload
# on an ALP host. It follows the steps documented in the URL provided below.
# Kea Workload Documentation: https://build.opensuse.org/package/view_file/SUSE:ALP:Workloads/kea-container/README.md?expand=1

- name: Deploying and Managing the Kea DHCP server workload
  hosts: alphost
  become: true
  vars:
    valid_lifetime: 4000
    renew_timer: 1000
    rebind_timer: 2000
    preferred_lifetime: 3000
    interface_name: 'eth0'
    lease_database_type: 'memfile'
    lease_database_persist: true
    lease_database_name: '/var/lib/kea/dhcp6.leases'
    subnet_id: 1
    subnet: '2001:db8:1::/64'
    pool_range: '2001:db8:1::1-2001:db8:1::ffff'
    workload:
      name: kea
      image: registry.opensuse.org/suse/alp/workloads/tumbleweed_containerfiles/suse/alp/workloads/kea:latest

  tasks:
    - name: Pull the Kea DHCP server container image
      containers.podman.podman_image:
        name: "{{ workload.image }}"
        state: present

    - name: Install all required parts of the Kea workload
      ansible.builtin.command: >-
        podman container runlabel install {{ workload.image }}
      register: workload_runlabel_install
      changed_when:
        - ('already exist' not in workload_runlabel_install.stdout)

    - name: Add firewall exception rule for DHCP
      ansible.posix.firewalld:
        service: dhcpv6
        permanent: true
        state: enabled
        immediate: true

    - name: Generate Kea DHCPv6 configuration from template
      ansible.builtin.template:
        src: "kea-dhcp6.conf.j2"
        dest: "/etc/kea/kea-dhcp6.conf"
        mode: '0644'
      register: dhcp6_config
      notify: Reload Kea configuration

    - name: Start Kea DHCPv6 server using systemd
      ansible.builtin.systemd:
        name: kea-dhcp6.service
        state: started
        enabled: true

  handlers:
    - name: Reload Kea configuration
      ansible.builtin.command: /usr/local/bin/keactrl reload
      changed_when:
        - dhcp6_config.changed
