- name: Disable lingering for user
  ansible.builtin.command:
    cmd: "loginctl disable-linger {{ ansible_user }}"

- name: Remove the resume-ansible-playbook.service service file
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/resume-ansible-playbook.service
    state: absent

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Conditionally end the playbook
  meta: end_play
