- name: Remove the myplaybook.service service file
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/myplaybook.service
    state: absent

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Conditionally end the playbook
  meta: end_play
